"""Court-oriented PDF rendering with provenance, privacy, and chain verification."""

from __future__ import annotations

from datetime import UTC, datetime
from hashlib import sha256
from io import BytesIO
from math import ceil
from pathlib import Path
from xml.sax.saxutils import escape

import reportlab
from reportlab.lib import colors
from reportlab.lib.enums import TA_CENTER
from reportlab.lib.pagesizes import A4
from reportlab.lib.styles import ParagraphStyle, getSampleStyleSheet
from reportlab.lib.units import mm
from reportlab.pdfbase import pdfmetrics
from reportlab.pdfbase.ttfonts import TTFont
from reportlab.platypus import (
    CondPageBreak,
    KeepTogether,
    PageBreak,
    Paragraph,
    SimpleDocTemplate,
    Spacer,
    Table,
    TableStyle,
)

_FONT_DIRECTORY = Path(reportlab.__file__).resolve().parent / "fonts"
pdfmetrics.registerFont(TTFont("CrimeLensSans", _FONT_DIRECTORY / "Vera.ttf"))
pdfmetrics.registerFont(TTFont("CrimeLensSans-Bold", _FONT_DIRECTORY / "VeraBd.ttf"))


def render_evidence_report(
    *, case, case_summary: str, officer, documents, entities, relationships, ledger_records,
    verification, export_event_id: str,
) -> tuple[bytes, str]:
    buffer = BytesIO()
    document = SimpleDocTemplate(
        buffer,
        pagesize=A4,
        leftMargin=18 * mm,
        rightMargin=18 * mm,
        topMargin=20 * mm,
        bottomMargin=18 * mm,
        title=f"CrimeLensAI Evidence Report {case.case_number}",
        author=officer.full_name,
        subject="Evidence provenance and tamper-evident audit report",
    )
    styles = getSampleStyleSheet()
    for style in styles.byName.values():
        style.fontName = "CrimeLensSans"
    styles.add(ParagraphStyle(name="ReportTitle", parent=styles["Title"], fontName="CrimeLensSans-Bold", alignment=TA_CENTER, textColor=colors.HexColor("#153B5B")))
    styles.add(ParagraphStyle(name="Fine", parent=styles["BodyText"], fontName="CrimeLensSans", fontSize=7.5, leading=9.5, textColor=colors.HexColor("#3D4A55")))
    styles.add(ParagraphStyle(name="Section", parent=styles["Heading2"], fontName="CrimeLensSans-Bold", textColor=colors.HexColor("#153B5B"), spaceBefore=8, spaceAfter=6))
    styles.add(ParagraphStyle(name="AuditHeading", parent=styles["Heading3"], fontName="CrimeLensSans-Bold", textColor=colors.HexColor("#153B5B")))
    story = [
        Paragraph("CrimeLensAI - Evidence Integrity Report", styles["ReportTitle"]),
        Spacer(1, 5 * mm),
        _table([
            ["Case number", case.case_number],
            ["Case title", case.title],
            ["Status / priority", f"{case.status.value} / {case.priority.value}"],
            ["Generated (UTC)", datetime.now(UTC).isoformat(timespec="seconds")],
            ["Generated by", f"{officer.full_name} ({officer.id}, {officer.role.value})"],
            ["Export audit event", export_event_id],
        ], [38 * mm, 132 * mm], styles),
        Spacer(1, 4 * mm),
        Paragraph(
            "Purpose: consolidate source provenance and tamper-evident audit metadata for authorized review. "
            "This report identifies investigative leads; it does not establish identity, guilt, or the truth of an allegation.",
            styles["BodyText"],
        ),
        Paragraph("Case summary", styles["Section"]),
        Paragraph(escape(case_summary), styles["BodyText"]),
        Paragraph("Evidence documents", styles["Section"]),
        _table(
            [["Document", "Type", "Bytes", "Processing", "Uploaded by"]]
            + [[item.original_filename, item.file_type.upper(), str(item.file_size_bytes), item.processing_status.value, item.uploaded_by] for item in documents]
            or [["No documents", "", "", "", ""]],
            [52 * mm, 18 * mm, 22 * mm, 28 * mm, 50 * mm],
            styles,
            header=True,
        ),
        Paragraph("Extracted entities and source provenance", styles["Section"]),
    ]

    if not entities:
        story.append(Paragraph("No extracted entities are stored for this case.", styles["BodyText"]))
    for entity in entities:
        occurrences = entity.properties.get("occurrences", []) if isinstance(entity.properties, dict) else []
        provenance = "; ".join(
            f"document={item.get('document_id', 'unknown')} offsets={item.get('start_offset', '?')}-{item.get('end_offset', '?')}"
            for item in occurrences[:8]
        ) or "No source offset recorded"
        story.append(KeepTogether([
            _table([
                ["Type / review", f"{entity.entity_type.value} / {entity.review_status}"],
                ["Value", entity.name],
                ["Confidence", f"{entity.confidence_score:.3f}"],
                ["Privacy", "MASKED VICTIM DATA" if entity.is_masked else "Standard case data"],
                ["Provenance", provenance],
            ], [34 * mm, 136 * mm], styles),
            Spacer(1, 2.5 * mm),
        ]))

    if relationships:
        story.append(KeepTogether([
            Paragraph("Evidence-backed relationships", styles["Section"]),
            _table(
                [["Type", "Source entity", "Target entity", "Confidence", "Evidence reference"]]
                + [[
                    item.relationship_type.value,
                    item.source_entity_id,
                    item.target_entity_id,
                    f"{item.confidence_score:.3f}",
                    str(item.properties.get("transaction_id") or item.properties.get("cdr_id") or item.source_document_id or "manual"),
                ] for item in relationships],
                [31 * mm, 38 * mm, 38 * mm, 20 * mm, 43 * mm], styles, header=True,
            ),
        ]))
    else:
        story.append(KeepTogether([
            Paragraph("Evidence-backed relationships", styles["Section"]),
            Paragraph("No reviewed relationships are stored for this case.", styles["BodyText"]),
        ]))

    story.extend([
        CondPageBreak(62 * mm),
        Paragraph("Tamper-evident audit verification", styles["Section"]),
        _table([
            ["Verification status", verification.status],
            ["Verified", "YES" if verification.verified else "NO"],
            ["Global records checked", str(verification.checked_records)],
            ["Ledger checkpoint sequence", str(verification.checked_through)],
            ["Checkpoint hash", verification.checkpoint_hash],
            ["Verification message", verification.message],
        ], [44 * mm, 126 * mm], styles),
        Spacer(1, 4 * mm),
        Paragraph(
            "Verification scope: the stored hash chain and its database checkpoint matched at generation time. "
            "This detects ordinary record alteration but cannot independently prove source evidence truth or prevent a privileged rewrite of both chain and checkpoint. "
            "Preserve the exported file checksum and an external checkpoint under agency evidence-handling procedures.",
            styles["Fine"],
        ),
        PageBreak(),
        Paragraph("Case audit entries (newest first)", styles["AuditHeading"]),
    ])
    audit_page_count = max(1, ceil(len(ledger_records) / 7))
    entries_per_page = max(1, ceil(len(ledger_records) / audit_page_count))
    for index, entry in enumerate(ledger_records):
        if index and index % entries_per_page == 0:
            story.extend([
                PageBreak(),
                Paragraph("Case audit entries (continued)", styles["AuditHeading"]),
            ])
        story.extend([CondPageBreak(34 * mm), KeepTogether([
            _table([
                ["Sequence / time", f"{entry.sequence} / {entry.timestamp}"],
                ["Action / actor", f"{entry.action} / {entry.actor}"],
                ["Resource", f"{entry.resource_type}:{entry.record_id}"],
                ["Previous hash", entry.previous_hash],
                ["Entry hash", entry.hash],
            ], [34 * mm, 136 * mm], styles),
            Spacer(1, 2.5 * mm),
        ])])

    def footer(canvas, doc):
        canvas.saveState()
        canvas.setFont("CrimeLensSans", 7)
        canvas.setFillColor(colors.HexColor("#52606D"))
        canvas.drawString(18 * mm, 9 * mm, f"Case {case.case_number} - CrimeLensAI evidence integrity report")
        canvas.drawRightString(192 * mm, 9 * mm, f"Page {doc.page}")
        canvas.restoreState()

    document.build(story, onFirstPage=footer, onLaterPages=footer)
    content = buffer.getvalue()
    return content, sha256(content).hexdigest()


def _table(rows, widths, styles, header: bool = False) -> Table:
    body_style = styles["Fine"]
    formatted = [[Paragraph(escape(str(cell)), body_style) for cell in row] for row in rows]
    table = Table(formatted, colWidths=widths, repeatRows=1 if header else 0, hAlign="LEFT")
    commands = [
        ("GRID", (0, 0), (-1, -1), 0.35, colors.HexColor("#9AA6B2")),
        ("VALIGN", (0, 0), (-1, -1), "TOP"),
        ("LEFTPADDING", (0, 0), (-1, -1), 4),
        ("RIGHTPADDING", (0, 0), (-1, -1), 4),
        ("TOPPADDING", (0, 0), (-1, -1), 3),
        ("BOTTOMPADDING", (0, 0), (-1, -1), 3),
    ]
    if header:
        commands.extend([
            ("BACKGROUND", (0, 0), (-1, 0), colors.HexColor("#DCE8F2")),
            ("FONTNAME", (0, 0), (-1, 0), "CrimeLensSans-Bold"),
        ])
    else:
        commands.extend([
            ("BACKGROUND", (0, 0), (0, -1), colors.HexColor("#EEF3F7")),
            ("FONTNAME", (0, 0), (0, -1), "CrimeLensSans-Bold"),
        ])
    table.setStyle(TableStyle(commands))
    return table
